/*
 * This Java source file was generated by the Gradle 'init' task.
 *
 * waidy
 */
package com.six311;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}

// eleven36
// six311
// six9

